services:
  url-shortner:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env.docker
  
  db:
    image: postgres:15.4
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=url-shortner
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
    driver: local